[package]
name = "rust_server"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
async-std = "1.12.0"
mdns-sd = "0.11.1"
