[package]
name = "rust_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6"
futures = "0.3"
openssl = "0.10"
tokio = { version = "1", features = ["full"] }
async-stream = "0.3"

